name: Build docker image on tag and push to registry

on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go Environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.19.2'

      - name: Extract Version
        id: branch_env
        shell: bash
        run: |
          echo "##[set-output name=version;]$(echo ${GITHUB_REF##*/})"

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install ginkgo
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo@v2.2.0
          sudo cp ~/go/bin/ginkgo /usr/local/bin
      
      - name: Run test cases
        working-directory: ./shop/
        run: |
          make e2e-test

      - name: Build and Push Image
        working-directory: ./shop/
        run: |
          make release-image
